// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2vCmXNfeBMWK_cNatkniFY3Ffkk6B5Uo',
    appId: '1:356079478763:web:d9d32615fa2221e7e25bae',
    messagingSenderId: '356079478763',
    projectId: 'activity-app-1cd6c',
    authDomain: 'activity-app-1cd6c.firebaseapp.com',
    storageBucket: 'activity-app-1cd6c.firebasestorage.app',
    measurementId: 'G-RJB2BG5XZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7nQ6SodZ9YQIGnmKwZzCiDJuubObwRx8',
    appId: '1:356079478763:android:dbb4fbc3d8669a74e25bae',
    messagingSenderId: '356079478763',
    projectId: 'activity-app-1cd6c',
    storageBucket: 'activity-app-1cd6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtESNB5L_gRPbyOLGohJC64pyq_4s4MlU',
    appId: '1:356079478763:ios:cfcab4334597c7ede25bae',
    messagingSenderId: '356079478763',
    projectId: 'activity-app-1cd6c',
    storageBucket: 'activity-app-1cd6c.firebasestorage.app',
    iosBundleId: 'com.example.activityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtESNB5L_gRPbyOLGohJC64pyq_4s4MlU',
    appId: '1:356079478763:ios:cfcab4334597c7ede25bae',
    messagingSenderId: '356079478763',
    projectId: 'activity-app-1cd6c',
    storageBucket: 'activity-app-1cd6c.firebasestorage.app',
    iosBundleId: 'com.example.activityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2vCmXNfeBMWK_cNatkniFY3Ffkk6B5Uo',
    appId: '1:356079478763:web:e2f881f51d087308e25bae',
    messagingSenderId: '356079478763',
    projectId: 'activity-app-1cd6c',
    authDomain: 'activity-app-1cd6c.firebaseapp.com',
    storageBucket: 'activity-app-1cd6c.firebasestorage.app',
    measurementId: 'G-LTDJ1E7EWJ',
  );
}
